/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StockQuoteWidget.java
 *
 * Created on 2011嚙踐��剖�頦����嚙踐�嚙賢�嚙�:44:35
 */
package teletext.apps.ui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import teletext.data.ChartDataService;
import teletext.data.ChartDataServiceListener;
import teletext.data.FCommand;
import teletext.data.StockInfoStore;

/**
 *
 * @author Hung
 */
public class StockQuoteWidget extends javax.swing.JPanel implements ChartDataServiceListener {

    private Image offImage = new ImageIcon(getClass().getResource("/rect.png")).getImage();
    private Image offImageX = new ImageIcon(getClass().getResource("/rectX.png")).getImage();
    private String symbol = "00001";
    private boolean withInX = false;

    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }
    private StockQuoteWidgetListener listener;

    public void addStockQuoteWidgetListener(StockQuoteWidgetListener ls) {
        listener = ls;
    }

    /** Creates new form StockQuoteWidget */
    public StockQuoteWidget() {
        initComponents();
    }

    public StockQuoteWidget(String symbol) {
        this.symbol = symbol;
        initComponents();
        this.lbCode.setText(symbol);
        String companyName = StockInfoStore.getInstance().getStockName(symbol);
        this.jLabel1.setText(companyName);
        FCommand fc = new FCommand(Integer.parseInt(symbol), FCommand.READQUOTE, this);
        ChartDataService.getInstance().addCommand(fc);
    }

    public void updateMarketData() {
        FCommand fc = new FCommand(Integer.parseInt(symbol), FCommand.READQUOTE, this);
        ChartDataService.getInstance().addCommand(fc);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        lbCode = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stockanalysisd.StockAnalysisDApp.class).getContext().getResourceMap(StockQuoteWidget.class);
        jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setName("Form"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCode.setFont(resourceMap.getFont("lbCode.font")); // NOI18N
        lbCode.setText(resourceMap.getString("lbCode.text")); // NOI18N
        lbCode.setName("lbCode"); // NOI18N
        add(lbCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 132, 31));

        lbPrice.setFont(resourceMap.getFont("lbPrice.font")); // NOI18N
        lbPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPrice.setText(resourceMap.getString("lbPrice.text")); // NOI18N
        lbPrice.setName("lbPrice"); // NOI18N
        add(lbPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 132, -1));

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 170, -1));

        lbTime.setText(resourceMap.getString("lbTime.text")); // NOI18N
        lbTime.setName("lbTime"); // NOI18N
        add(lbTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        System.out.println(evt.getX() + ":" + evt.getY());
        if ((this.getWidth() - evt.getX()) < 20 && evt.getY() < 20) {
            listener.onWidgentCloseEvent(this);
        } else {
            updateMarketData();
        }
        updateMarketData();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        if ((this.getWidth() - evt.getX()) < 20 && evt.getY() < 20) {
            withInX = true;
            this.repaint();

        } else {
            if (withInX) {
                withInX = false;
                repaint();
            }
        }
    }//GEN-LAST:event_formMouseMoved

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        if (withInX) {
            withInX = false;
            repaint();
        }
    }//GEN-LAST:event_formMouseExited
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbCode;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbTime;
    // End of variables declaration//GEN-END:variables

    public void paint(Graphics g) {
        if (offImage != null) {

            if (!withInX) {
                g.drawImage(offImage, 0, 0, getSize().width, getSize().height, this);
            } else {
                g.drawImage(offImageX, 0, 0, getSize().width, getSize().height, this);
            }
            //g.drawRect(0, 0, getSize().width - 1, getSize().height - 1);
            this.paintComponents(g);
        } else {
            super.paint(g);
        }
    }

    public void OnReceivedChartData(FCommand fc, Object result) {
        lbPrice.setText((String) result);
        String code = "00000" + fc.getCode();
        this.symbol = code.substring(code.length() - 5);
        String time = new SimpleDateFormat("hh:mm:ss").format(new Date());
        lbTime.setText(time);
        lbTime.setForeground(Color.red);
    }

    public void OnReceivedError(FCommand fc) {
        lbPrice.setText("N/A");

    }

    public void OnProgress(int percent) {
        // throw new UnsupportedOperationException("Not supported yet.");
    }

    public int getWidth() {
        return 214;
    }

    public int getHeight() {
        return 135;
    }
}
