/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StockQuotePanel.java
 *
 * Created on 2011�蕭嚙踝蕭7嚙踝蕭 ��嚙�0:34:28
 */
package teletext.apps.ui;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import teletext.data.FCommand;
import teletext.data.RealTimeFeed;
import teletext.util.FormatUtil;

/**
 *
 * @author Hung
 */
public class StockQuotePanel extends javax.swing.JPanel implements StockQuoteWidgetListener {
 

    /** Creates new form StockQuotePanel */
    public StockQuotePanel() {
        initComponents();
        loadFromFile();
        if (widgets.size() == 0) {
            widgets.put("00001", new StockQuoteWidget("00001"));
            symbols.add("00001");
        }
        initWidgetComponents();
        //updateMarketData();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfCode = new javax.swing.JTextField();
        btReload = new javax.swing.JButton();
        cbRealTime = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stockanalysisd.StockAnalysisDApp.class).getContext().getResourceMap(StockQuotePanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        tfCode.setFont(resourceMap.getFont("tfCode.font")); // NOI18N
        tfCode.setText(resourceMap.getString("tfCode.text")); // NOI18N
        tfCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tfCode.setName("tfCode"); // NOI18N
        tfCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCode_keyPressed(evt);
            }
        });

        btReload.setText(resourceMap.getString("btReload.text")); // NOI18N
        btReload.setName("btReload"); // NOI18N
        btReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReloadActionPerformed(evt);
            }
        });

        cbRealTime.setText(resourceMap.getString("cbRealTime.text")); // NOI18N
        cbRealTime.setName("cbRealTime"); // NOI18N
        cbRealTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRealTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tfCode, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 419, Short.MAX_VALUE)
                .addComponent(btReload, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbRealTime)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btReload, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(cbRealTime))
                .addContainerGap())
        );

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentResized(evt);
            }
        });
        jPanel2.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentResized
        // TODO add your handling code here:
        initWidgetComponents();
    }//GEN-LAST:event_jPanel2ComponentResized

    private void tfCode_keyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCode_keyPressed
        if (evt.getKeyCode() == 10) {
            String cc = "00000" + tfCode.getText().trim();

            if (!FormatUtil.isNumerical(cc)) {
                this.tfCode.setText("");
                return;
            }
            cc = cc.substring(cc.length() - 5);
            int Code = Integer.parseInt(cc);
            this.tfCode.setText("");
            if (!widgets.containsKey(cc)) {
                StockQuoteWidget widget = new StockQuoteWidget(cc.trim());
                widget.updateMarketData();
                widgets.put(cc.trim(), widget);
                symbols.add(widget.getSymbol());
                initWidgetComponents();
            }
        }
    }//GEN-LAST:event_tfCode_keyPressed

    private void btReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReloadActionPerformed
        // TODO add your handling code here:
        this.updateMarketData();
    }//GEN-LAST:event_btReloadActionPerformed

    private void cbRealTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRealTimeActionPerformed
        // TODO add your handling code here:

        if (cbRealTime.isSelected()) {
            System.out.println("Realtime on");
            
            ArrayList fcs = new ArrayList<FCommand>();
            for (String symbol: symbols){
                StockQuoteWidget widget = widgets.get(symbol);
                FCommand fc = new FCommand(Integer.parseInt(symbol), FCommand.READQUOTE, widget);
                fcs.add(fc);
            }
            RealTimeFeed.getInstance().startFeed(fcs);
        } else {
            System.out.println("Realtime off");
            RealTimeFeed.getInstance().stopFeed();
        }
    }//GEN-LAST:event_cbRealTimeActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReload;
    private javax.swing.JCheckBox cbRealTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfCode;
    // End of variables declaration//GEN-END:variables
    private Hashtable<String, StockQuoteWidget> widgets = new Hashtable<String, StockQuoteWidget>();
    private LinkedList<String> symbols = new LinkedList<String>();

    protected void updateMarketData() {
        for (StockQuoteWidget widget : widgets.values()) {
            widget.updateMarketData();
        }

    }

    protected void initWidgetComponents() {
        //this.removeAll();
        int row = 1;
        int column = 1;
        for (String symbol : symbols) {
            //for (StockQuoteWidget widget : widgets.values()) {
            StockQuoteWidget widget = widgets.get(symbol);
            if (widget == null) {
                continue;
            }
            jPanel2.add(widget, null);
            widget.addStockQuoteWidgetListener(this);
            int y = 10 * row + widget.getHeight() * (row - 1);
            int x = 10 * column + widget.getWidth() * (column - 1);
            widget.setBounds(x, y, widget.getWidth(), widget.getHeight());
            //row ++;
            column++;
            x = 10 * column + widget.getWidth() * (column - 1);
            
            if (x + widget.getWidth() > jPanel2.getWidth()) {
                row++;
                column = 1;
            }
        }
    }

    public void onWidgentCloseEvent(StockQuoteWidget widget) {
        widgets.remove(widget.getSymbol());
        jPanel2.remove(widget);
        symbols.remove(widget.getSymbol());
        initWidgetComponents();
        jPanel2.repaint();

    }

    public void saveToFile() {
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter("quote.save"));
            for (String symbol : symbols) {
                writer.write(symbol);
                writer.write(";");
            }
            writer.flush();
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(StockQuotePanel.class.getName()).log(Level.SEVERE, "Failed to save quote config.", ex);
        }
    }

    public void loadFromFile() {
        try {
            BufferedReader reader = new BufferedReader(new FileReader("quote.save"));
            String line = reader.readLine();
            if (line == null || line.trim().equals("")) {
                return;
            }
            String quotes[] = line.split(";");
            for (int i = 0; i < quotes.length; i++) {
                widgets.put(quotes[i], new StockQuoteWidget(quotes[i]));
                symbols.add(quotes[i]);
            }
        } catch (IOException ex) {
            Logger.getLogger(StockQuotePanel.class.getName()).log(Level.SEVERE, "Failed to load quote confi.", ex);
        }

    }
}
