/*
 * StockAnalysisDView.java
 */
package stockanalysisd;

import teletext.apps.core.ChartScreen;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import teletext.apps.ui.FConfig;
import teletext.data.ChartDataService;
import teletext.data.FCommand;

/**
 * The application's main frame.
 */
public class StockAnalysisDView extends FrameView {

    public StockAnalysisDView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // FMEChartA fmeChartA = new FMEChartA();
        // mainPanel.add(fmeChartA,BorderLayout.CENTER);
        // mainPanel.setVisible(true);
        // mainPanel.setSize(600,400);
        // fmeChartA.setSize(600,400);

        // frame.setSize(600, 400);

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {

            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                Logger.getLogger("DEFAULT").fine("propertyName: " + propertyName );
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String) (evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer) (evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });


        loadResource();
        

    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = StockAnalysisDApp.getApplication().getMainFrame();
            aboutBox = new StockAnalysisDAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        StockAnalysisDApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        mainPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        fMEChartA1 = new teletext.apps.ui.FMEChartA();
        stockQuotePanel1 = new teletext.apps.ui.StockQuotePanel();

        menuBar.setName("menuBar"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(stockanalysisd.StockAnalysisDApp.class).getContext().getResourceMap(StockAnalysisDView.class);
        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText(resourceMap.getString("saveMenuItem.text")); // NOI18N
        saveMenuItem.setName("saveMenuItem"); // NOI18N
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(stockanalysisd.StockAnalysisDApp.class).getContext().getActionMap(StockAnalysisDView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 642, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                mainPanelComponentResized(evt);
            }
        });
        mainPanel.setLayout(new java.awt.CardLayout());

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        fMEChartA1.setName("fMEChartA1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("fMEChartA1.TabConstraints.tabTitle"), fMEChartA1); // NOI18N

        stockQuotePanel1.setName("stockQuotePanel1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("stockQuotePanel1.TabConstraints.tabTitle"), stockQuotePanel1); // NOI18N

        mainPanel.add(jTabbedPane1, "card2");

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void mainPanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_mainPanelComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_mainPanelComponentResized

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
       stockQuotePanel1.saveToFile();
    }//GEN-LAST:event_saveMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private teletext.apps.ui.FMEChartA fMEChartA1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private teletext.apps.ui.StockQuotePanel stockQuotePanel1;
    // End of variables declaration//GEN-END:variables
    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;
    private JDialog aboutBox;

    public void loadResource() {

        try {
            fMEChartA1.fbuttonBar.btWatch.setButtonImage(new ImageIcon(getClass().getResource("/watch.gif")).getImage());
            // load image from URL
            fMEChartA1.fbuttonBar.btNone.setButtonImage(new ImageIcon(getClass().getResource("/mouse.gif")).getImage());
            fMEChartA1.fbuttonBar.btWatch.setButtonImage(new ImageIcon(getClass().getResource("/watch.gif")).getImage());
            fMEChartA1.fbuttonBar.btZoomIn.setButtonImage(new ImageIcon(getClass().getResource("/zoomin.gif")).getImage());
            fMEChartA1.fbuttonBar.btZoomOut.setButtonImage(new ImageIcon(getClass().getResource("/zoomout.gif")).getImage());
            fMEChartA1.fbuttonBar.btMove.setButtonImage(new ImageIcon(getClass().getResource("/move.gif")).getImage());
            fMEChartA1.fbuttonBar.btInsertLine.setButtonImage(new ImageIcon(getClass().getResource("/insertline.gif")).getImage());
            fMEChartA1.fbuttonBar.btInsertPLine.setButtonImage(new ImageIcon(getClass().getResource("/parallelline.gif")).getImage());
            fMEChartA1.fbuttonBar.btGPartition.setButtonImage(new ImageIcon(getClass().getResource("/goldenpartition.gif")).getImage());
            fMEChartA1.fbuttonBar.btRemoveLine.setButtonImage(new ImageIcon(getClass().getResource("/removeline.gif")).getImage());
            fMEChartA1.fbuttonBar.btClear.setButtonImage(new ImageIcon(getClass().getResource("/clear.gif")).getImage());
            fMEChartA1.fbuttonBar.btCompare.setButtonImage(new ImageIcon(getClass().getResource("/compare.gif")).getImage());
            fMEChartA1.fbuttonBar.btSetting.setButtonImage(new ImageIcon(getClass().getResource("/setting.png")).getImage());
            fMEChartA1.fTAMenu1.btSetting.setButtonImage(new ImageIcon(getClass().getResource("/setting.png")).getImage());
            fMEChartA1.chartOptionBar1.btStock.setButtonImage(new ImageIcon(getClass().getResource("/SS.gif")).getImage());
            fMEChartA1.chartOptionBar1.btTA.setButtonImage(new ImageIcon(getClass().getResource("/ST.gif")).getImage());
            fMEChartA1.chartOptionBar1.btVolume.setButtonImage(new ImageIcon(getClass().getResource("/SV.gif")).getImage());
            fMEChartA1.btOpenClose.setButtonImage(new ImageIcon(getClass().getResource("/open.gif")).getImage());
            fMEChartA1.btPrinter.setButtonImage(new ImageIcon(getClass().getResource("/printer.gif")).getImage());

            //loginPanel.setButtonImage(getImage(getDocumentBase(), "screen.gif");
            //oginPanel.setButtonImage(getImage(getDocumentBase(), "screen.gif");
            //oginPanel.repaint();
            // Init the chart screen
            fMEChartA1.chartScreen1.initScreen();
            fMEChartA1.chartScreen2.initScreen();
            fMEChartA1.chartScreen3.initScreen();

            ChartDataService.getInstance().enable();

            // add a chart data
            FCommand fc = new FCommand(0001, FCommand.TYPE_DOWNLOAD_LEFT_CHART, fMEChartA1.fmenuBar.chDuration.getSelectedIndex(), "LMain1", 500, 1, false, fMEChartA1.fmenuBar);
            ChartDataService.getInstance().addCommand(fc);
            fMEChartA1.chartScreen1.setScreenState(ChartScreen.LOADING);
            fMEChartA1.chartScreen2.setScreenState(ChartScreen.LOADING);
            fMEChartA1.chartScreen3.setScreenState(ChartScreen.LOADING);

            // change the language by calling set language function
            fMEChartA1.SetLanguage(FConfig.constChinese);
        } catch (Throwable e) {
            e.printStackTrace();

        }
    }

  
}



